services:
    sharepai.oss.listener:
        class: sharepai\oss\event\main_listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
